### ISSUE TITLE
Support multiple phone numbers for a person

### ISSUE THREAD

**Issue by xhsien** [CS2103AUG2017-W10-B3/main#15]
@CS2103AUG2017-W10-B3/developers do we want to add tags for different phone numbers? Eg. work/home/personal

**Comment by chilipadiboy** [comment]
I think its just a lot of work for the same thing tbh unless theres a nicer way of implementing it.

is your idea smth like  wp/12314 pp/123123 hp/123123123?

**Comment by Jemereny** [comment]
I think its a great idea.
What @chilipadiboy mentioned about the wp/ pp/ hp/ prefixes is great.
What do you think should the "required" number to be put in? Or would any of them do?

**Comment by xhsien** [comment]
Yes, I like the idea of mentioned by @chilipadiboy! After some thinking, I suggest having these attributes:

- `mp/` for mobile.
- `wp/` for work.
- `hp/` for home.

Any thoughts on this? Otherwise, I can start to work.

**Comment by xhsien** [comment]
We decided to close this.
