### ISSUE TITLE
Find user by birthday

### ISSUE THREAD

**Issue by Jemereny** [CS2103AUG2017-W10-B3/main#24]
As a user, I can find users by birthdays so I know whose birthday is on that month.

**Comment by xhsien** [comment]
> so I know whose birthday is on that month.

Does that mean they do something like `find 1`, `find 2` for people born in January and February respectively?

**Comment by Jemereny** [comment]
It would either be first three letters of the month or a number from 1-12. Which do you think will be better?

**Comment by Jemereny** [comment]
Also, I think for /find commands we could start to use prefixes as well so we can identify what are we actually looking for. E.g. find t/ | find b/ | find n/

**Comment by chilipadiboy** [comment]
i think can be both cause its not like theres many way to represent a month. also dates are stored in a fixed format already i.e. 01 02 03....12 s

maybe can have a case thing for each month e.g case 1: if (input == 2 || input == 02 || input == "feb" || input == "february") return all the feb babies

SHould have 12 cases plus the base case that is invalid input.

**Comment by xhsien** [comment]
I agree that if we allow a user to find something other than names, we will have to add prefixes. e.g

- `find t/friend`
- `find n/David`
- `find b/January`

Or we can be even more complex:

- `find n/David t/friend`

that returns person that has "David" in their name and with a "friend" tag. What do you think?
