### ISSUE TITLE
Suggestion on `find` command

### ISSUE THREAD

**Issue by yanji1221** [CS2103AUG2017-W10-B3/main#75]
![image](https://user-images.githubusercontent.com/22042886/32363247-4d3bbb4a-c0a9-11e7-8575-f761807e631a.png)

If I only want to find a specific person: Amy Wang, it will show Amy Wang and Amy Wong as Amy appears in both name. Thus, if I have many friend named Amy, the list will still be long, I think this will be a bit inconvenient. Maybe if the user want to find multiple people, they can enter: find n/person1 n/person2 instead of n/person1 person2 person3...

**Comment by xhsien** [comment]
Thanks for the feedback. This is very helpful!
