### ISSUE TITLE
A minor problem when changing theme

### ISSUE THREAD

**Issue by yanji1221** [CS2103AUG2017-W10-B3/main#76]
When I change the theme from dark to light, or light to dark, the scroll bar of the browser panel will change color only when I move my mouse on it. 

![image](https://user-images.githubusercontent.com/22042886/32363418-3f67ea7e-c0aa-11e7-8c24-57b3c1ded8d4.png)

**Comment by Houjisan** [comment]
Another problem I found:
Although theme can be undone and redone in the app, the theme does not change actually and remains the same theme.
